# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tv_image = QtWidgets.QLabel(self.centralwidget)
        self.tv_image.setGeometry(QtCore.QRect(20, 20, 451, 235))
        self.tv_image.setText("")
        self.tv_image.setPixmap(QtGui.QPixmap("pictures/off.png"))
        self.tv_image.setObjectName("tv_image")
        self.power_button = QtWidgets.QPushButton(self.centralwidget)
        self.power_button.setGeometry(QtCore.QRect(180, 390, 131, 51))
        self.power_button.setObjectName("power_button")
        self.channelUp_button = QtWidgets.QPushButton(self.centralwidget)
        self.channelUp_button.setGeometry(QtCore.QRect(30, 350, 90, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.channelUp_button.setFont(font)
        self.channelUp_button.setObjectName("channelUp_button")
        self.channelDown_button = QtWidgets.QPushButton(self.centralwidget)
        self.channelDown_button.setGeometry(QtCore.QRect(30, 430, 90, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.channelDown_button.setFont(font)
        self.channelDown_button.setObjectName("channelDown_button")
        self.volumeUp_button = QtWidgets.QPushButton(self.centralwidget)
        self.volumeUp_button.setGeometry(QtCore.QRect(370, 350, 90, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.volumeUp_button.setFont(font)
        self.volumeUp_button.setObjectName("volumeUp_button")
        self.volumeDown_button = QtWidgets.QPushButton(self.centralwidget)
        self.volumeDown_button.setGeometry(QtCore.QRect(370, 430, 90, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.volumeDown_button.setFont(font)
        self.volumeDown_button.setObjectName("volumeDown_button")
        self.mute_button = QtWidgets.QPushButton(self.centralwidget)
        self.mute_button.setGeometry(QtCore.QRect(200, 480, 90, 51))
        self.mute_button.setObjectName("mute_button")
        self.channel_label = QtWidgets.QLabel(self.centralwidget)
        self.channel_label.setGeometry(QtCore.QRect(40, 330, 51, 16))
        self.channel_label.setObjectName("channel_label")
        self.volume_label = QtWidgets.QLabel(self.centralwidget)
        self.volume_label.setGeometry(QtCore.QRect(380, 330, 51, 16))
        self.volume_label.setObjectName("volume_label")
        self.channel_num = QtWidgets.QLabel(self.centralwidget)
        self.channel_num.setGeometry(QtCore.QRect(100, 330, 31, 16))
        self.channel_num.setText("")
        self.channel_num.setObjectName("channel_num")
        self.volume_num = QtWidgets.QLabel(self.centralwidget)
        self.volume_num.setGeometry(QtCore.QRect(430, 330, 31, 16))
        self.volume_num.setText("")
        self.volume_num.setObjectName("volume_num")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.power_button.setText(_translate("MainWindow", "Power"))
        self.channelUp_button.setText(_translate("MainWindow", "+"))
        self.channelDown_button.setText(_translate("MainWindow", "-"))
        self.volumeUp_button.setText(_translate("MainWindow", "+"))
        self.volumeDown_button.setText(_translate("MainWindow", "-"))
        self.mute_button.setText(_translate("MainWindow", "Mute"))
        self.channel_label.setText(_translate("MainWindow", "Channel"))
        self.volume_label.setText(_translate("MainWindow", "Volume"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
